NUM_OCEAN_FEATURES = 5

# positions
X = 0
Y = 1
NUM_CHICKENS = 10

CLOSENESS_THRESHOLD = .03
MOVE_AMOUNT = .03

STEP_REWARD = -.001
ARRIVAL_REWARD = 1.0
TIMEOUT_REWARD = -1.0
NUM_DIRECTIONS = 8
TIMEOUT = 1000

YOUR_ROOT = '/Users/jmugan/ray_results/YourTrainer'
